[log]
level = "debug,sqlx=debug"
format = "text"            # Возможные значения: "json" или "text"



[clickhouse]
timeout = 30   # seconds
pool_min = 5
pool_max = 20

[tinkoff_api]
base_url = "https://invest-public-api.tinkoff.ru:443"
domain = "invest-public-api.tinkoff.ru"
timeout = 30   # seconds
keepalive = 60 # seconds

[tinkoff_market_data_updater]
enabled = true
interval_seconds = 300  # секунды
start_time = "21:00:00"     # 0:00 Moscow time (UTC+3)
end_time = "04:00:00"       # 7:00 Moscow time (UTC+3)



[historical_candle_data]
enabled = false                # Включить/выключить сервис загрузки исторических свечей
request_delay_ms = 200        # Задержка между API запросами в мс (для избежания лимитов API)
start_time = "04:00:00"     # 7:00 Moscow time (UTC+3)
end_time = "21:00:00"       # 0:00 Moscow time (UTC+3)

