[log]
level = "info,sqlx=info"
format = "text"            # Возможные значения: "json" или "text"

[postgres]
timeout = 30               # seconds
max_connections = 40
min_connections = 10
max_lifetime = 1800        # 30 minutes
idle_timeout = 600         # 10 minutes

[clickhouse]
timeout = 30   # seconds

[tinkoff_api]
base_url = "https://invest-public-api.tinkoff.ru:443"
domain = "invest-public-api.tinkoff.ru"
timeout = 30   # seconds
keepalive = 60 # seconds

[shares_scheduler]
enabled = true
initial_run = true        # Запускать ли обновление инструментов при старте приложения
interval_seconds = 300      # секунды
start_time = "04:00:00"     # 7:00 Moscow time (UTC+3)
end_time = "21:00:00"       # 00:00 Moscow time (UTC+3)



[candles_scheduler]
enabled = true                # Включить/выключить сервис загрузки исторических свечей
initial_run = true          # Запускать ли обновление исторических свечей при старте приложения
request_delay_ms = 200        # Задержка между API запросами в мс (для избежания лимитов API)
start_time = "21:00:00"     # 0:00 Moscow time (UTC+3)
end_time = "04:00:00"       # 7:00 Moscow time (UTC+3)

