name: Docker Build and Publish

on:
  push:
    tags:
      - '*.*.*' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Extract tag name
        id: tag
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            wayofdt/t-candles:latest
            wayofdt/t-candles:${{ steps.tag.outputs.version }}
          target: production
          cache-from: type=registry,ref=wayofdt/t-candles:buildcache
          cache-to: type=registry,ref=wayofdt/t-candles:buildcache,mode=max